theme: jekyll-theme-minimal
title: Translational Immunogenomics Lab @ UNC
description: Collective of researchers at UNC Chapel Hill using experimental and computational immunology, genomics, and machine learning to create personalized immunotherapies and bring them to the clinic. 
logo: https://til-unc.github.io/logo.png
github_username: til-unc

# Copied configuration from https://github.com/barryclark/jekyll-now/blob/master/_config.yml

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
