theme: jekyll-theme-minimal
title: Translational Immunogenomics Lab @ UNC
description: Collective of researchers at UNC Chapel Hill using experimental and computational immunology, genomics, and machine learning to create personalized immunotherapies and bring them to the clinic. 
logo: https://til-unc.github.io/logo.png
github_username: iskandr
